### ISSUE TITLE
[QUESTION] Issue with Truemail Docker Setup: Invalid Access Token Error

### ISSUE THREAD

**Issue by Tanjohnson99** [truemail-rb/truemail-rack-docker-image#92]
Hello,

I'm currently trying to use Truemail with Docker and Portainer. I've set up the docker-compose.yml file as follows:

However, when accessing the web interface, I'm getting an "invalid truemail access token" error. I've double-checked the token, and it seems to be correct. Could you please provide guidance on how to resolve this issue?

Thank you.

**Comment by bestwebua** [comment]
Hi, @Tanjohnson99! Here is an example of `docker-compose.yml`:

```yml
# docker-compose.yml

version: "3.7"

services:
  truemail:
    image: truemail/truemail-rack:latest
    ports:
      - 9292:9292
    environment:
      VERIFIER_EMAIL: your_email@example.com
      ACCESS_TOKENS: your_token # here is your access token
    tty: true
```

And here is an example of http-request:

```bash
curl -i -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: your_token" http://localhost:9292?email=some_email_to_verify@gmail.com
```

It works, please check out it.
